// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NicknameAvailability struct {
	Available bool    `json:"available"`
	Message   *string `json:"message,omitempty"`
}

type Query struct {
}

type UpdateProfileInput struct {
	Nickname     *string `json:"nickname,omitempty"`
	Bio          *string `json:"bio,omitempty"`
	ProfileImage *string `json:"profileImage,omitempty"`
	Theme        *string `json:"theme,omitempty"`
}

type UserProfile struct {
	ID             string  `json:"id"`
	UserID         string  `json:"userID"`
	Nickname       string  `json:"nickname"`
	Bio            *string `json:"bio,omitempty"`
	ProfileImage   *string `json:"profileImage,omitempty"`
	Theme          string  `json:"theme"`
	FollowerCount  int32   `json:"followerCount"`
	FollowingCount int32   `json:"followingCount"`
}
