package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"

	"github.com/rainbow96bear/planet_user_server/graph/model"
	"github.com/rainbow96bear/planet_utils/pkg/logger"
)

// CheckNicknameAvailability is the resolver for the checkNicknameAvailability field.
func (r *queryResolver) CheckNicknameAvailability(ctx context.Context, nickname string) (*model.NicknameAvailability, error) {
	available, err := r.ProfileService.IsNicknameAvailable(ctx, nickname)
	if err != nil {
		logger.Errorf("%s", err.Error())
		msg := "서버 오류가 발생했습니다"
		return &model.NicknameAvailability{
			Available: false,
			Message:   &msg,
		}, nil
	}

	var msg *string
	if !available {
		m := "이미 사용 중인 닉네임입니다"
		msg = &m
	}

	return &model.NicknameAvailability{
		Available: available,
		Message:   msg,
	}, nil
}
