package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"errors"
	"fmt"

	jwt "github.com/golang-jwt/jwt/v5"
	"github.com/google/uuid"
	"github.com/rainbow96bear/planet_user_server/dto"
	"github.com/rainbow96bear/planet_user_server/graph/model"
	"github.com/rainbow96bear/planet_user_server/internal/planet_err"
	"github.com/rainbow96bear/planet_user_server/middleware"
	"github.com/rainbow96bear/planet_utils/pkg/logger"
)

// UpdateMyProfile is the resolver for the updateMyProfile field.
func (r *mutationResolver) UpdateMyProfile(ctx context.Context, input model.UpdateProfileInput) (*model.UserProfile, error) {
	logger.Infof("UpdateMyProfile start")
	// Authorization 헤더에서 access token 가져오기
	token, err := middleware.ExtractAccessToken(ctx)
	if err != nil {
		return nil, err
	}

	logger.Debugf("access token : %s", token)

	// JWT 디코딩 (서명 검증은 서비스에서 처리할 수도 있음)

	claims, ok := token.Claims.(jwt.MapClaims)
	if !ok {
		return nil, errors.New("invalid token claims")
	}

	// JWT에서 userID 추출
	userIDStr, ok := claims["sub"].(string)
	if !ok {
		return nil, errors.New("user id not found in token")
	}

	userID, err := uuid.Parse(userIDStr)
	if err != nil {
		return nil, fmt.Errorf("invalid user id format: %w", err)
	}

	// DTO 생성
	updateDTO := &dto.ProfileUpdate{
		UserID:       userID,
		Nickname:     input.Nickname,
		Bio:          input.Bio,
		ProfileImage: input.ProfileImage,
		Theme:        input.Theme,
	}

	// 서비스 호출
	updatedDTO, err := r.ProfileService.UpdateProfile(ctx, userID, updateDTO)
	if err != nil {
		// 닉네임 중복 오류 처리
		if errors.Is(err, planet_err.ErrNicknameDuplicate) {
			return nil, planet_err.ErrNicknameDuplicate
		}
		return nil, fmt.Errorf("failed to update profile: %w", err)
	}

	// DTO -> GraphQL 모델 변환
	updatedProfile := &model.UserProfile{
		ID:             updatedDTO.ID,
		UserID:         updatedDTO.UserID.String(), // uuid.UUID -> string
		Nickname:       updatedDTO.Nickname,
		Bio:            &updatedDTO.Bio,
		ProfileImage:   &updatedDTO.ProfileImage,
		Theme:          updatedDTO.Theme,
		FollowerCount:  updatedDTO.FollowerCount,
		FollowingCount: updatedDTO.FollowingCount,
	}

	return updatedProfile, nil
}

// MyProfile is the resolver for the myProfile field.
func (r *queryResolver) MyProfile(ctx context.Context) (*model.UserProfile, error) {
	logger.Infof("GetMyProfileInfo start")
	defer logger.Infof("GetMyProfileInfo end")

	token, err := middleware.ExtractAccessToken(ctx)
	if err != nil {
		return nil, err
	}

	logger.Debugf("access token : %s", token)

	claims, ok := token.Claims.(jwt.MapClaims)
	if !ok {
		return nil, errors.New("invalid token claims")
	}

	// user id 추출
	userIDStr, ok := claims["sub"].(string) // JWT 표준 claim(sub)
	if !ok {
		return nil, errors.New("user id not found in token")
	}

	// 문자열 → uuid.UUID 변환
	userID, err := uuid.Parse(userIDStr)
	if err != nil {
		return nil, errors.New("invalid UUID in token")
	}

	// service 호출
	dtoProfile, err := r.ProfileService.GetMyProfileInfo(ctx, userID)
	if err != nil {
		return nil, err
	}

	// DTO → GraphQL 타입 변환
	return &model.UserProfile{
		ID:             dtoProfile.ID,
		UserID:         dtoProfile.UserID.String(),
		Nickname:       dtoProfile.Nickname,
		Bio:            &dtoProfile.Bio,
		ProfileImage:   &dtoProfile.ProfileImage,
		FollowerCount:  dtoProfile.FollowerCount,
		FollowingCount: dtoProfile.FollowingCount,
		Theme:          dtoProfile.Theme,
	}, nil
}

// UserProfile is the resolver for the userProfile field.
func (r *queryResolver) UserProfile(ctx context.Context, userID string) (*model.UserProfile, error) {
	logger.Infof("GetUserProfile start, userID=%s", userID)
	defer logger.Infof("GetUserProfile end, userID=%s", userID)

	// 1. userID 파싱
	parsedUserID, err := uuid.Parse(userID)
	if err != nil {
		logger.Warnf("invalid userID format: %s", userID)
		return nil, errors.New("invalid user id")
	}

	// 2. 서비스 호출 (공개 프로필 조회)
	dtoProfile, err := r.ProfileService.GetUserProfileInfo(ctx, parsedUserID)
	if err != nil {
		logger.Errorf(
			"GetUserProfile failed, userID=%s, err=%v",
			userID,
			err,
		)
		return nil, err
	}

	// 3. DTO → GraphQL Model 변환
	result := &model.UserProfile{
		ID:             dtoProfile.ID,
		UserID:         dtoProfile.UserID.String(),
		Nickname:       dtoProfile.Nickname,
		FollowerCount:  dtoProfile.FollowerCount,
		FollowingCount: dtoProfile.FollowingCount,
		Theme:          dtoProfile.Theme,
	}

	if dtoProfile.Bio != "" {
		result.Bio = &dtoProfile.Bio
	}
	if dtoProfile.ProfileImage != "" {
		result.ProfileImage = &dtoProfile.ProfileImage
	}

	return result, nil
}
