package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"errors"
	"fmt"

	"github.com/google/uuid"
	"github.com/rainbow96bear/planet_user_server/graph"
	"github.com/rainbow96bear/planet_user_server/internal/models"
	"github.com/rainbow96bear/planet_user_server/middleware"
	"github.com/rainbow96bear/planet_user_server/utils"
)

// UpdateTodoDone is the resolver for the updateTodoDone field.
func (r *mutationResolver) UpdateTodoDone(ctx context.Context, id string, isDone bool) (*models.Todo, error) {
	// 인증
	token, err := middleware.ExtractAccessToken(ctx)
	if err != nil {
		return nil, errors.New("unauthorized")
	}

	userID, err := utils.GetUserID(token)
	if err != nil {
		return nil, errors.New("unauthorized")
	}

	// ID 변환
	todoID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid todo id")
	}

	// 서비스 호출
	return r.TodoService.UpdateTodoStatus(
		ctx,
		userID,
		todoID,
		isDone,
	)
}

// Todo is the resolver for the todo field.
func (r *queryResolver) Todo(ctx context.Context, id string) (*models.Todo, error) {
	// 1️⃣ 인증
	token, err := middleware.ExtractAccessToken(ctx)
	if err != nil {
		return nil, errors.New("unauthorized")
	}

	userID, err := utils.GetUserID(token)
	if err != nil {
		return nil, errors.New("unauthorized")
	}

	// 2️⃣ id → uuid
	todoID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid todo id")
	}

	// 3️⃣ 서비스 조회
	todo, err := r.TodoService.FindByID(ctx, userID, todoID)
	if err != nil {
		return nil, err
	}

	if todo == nil {
		return nil, fmt.Errorf("todo not found")
	}

	return todo, nil
}

// ID is the resolver for the id field.
func (r *todoResolver) ID(ctx context.Context, obj *models.Todo) (string, error) {
	if obj == nil {
		return "", nil
	}
	return obj.ID.String(), nil
}

// CalendarEventID is the resolver for the calendarEventId field.
func (r *todoResolver) CalendarEventID(ctx context.Context, obj *models.Todo) (*string, error) {
	if obj == nil {
		return nil, nil
	}
	id := obj.CalendarEventID.String()
	return &id, nil
}

// Todo returns graph.TodoResolver implementation.
func (r *Resolver) Todo() graph.TodoResolver { return &todoResolver{r} }

type todoResolver struct{ *Resolver }
